### ISSUE TITLE
No supported memory found

### ISSUE THREAD

**Issue by mashkovtsev2006** [IndeedMiners/PolarisBiosEditor#12]
GV-RX570GAMING-8GD/FI1/0A2B
H5GC8H24AJ (HYNIX_4)

555000000000000022AA1C0063941211205F0A0A1244B10200204100330214209A8800A00000312006040C0E2B11130F
777000000000000022AA1C00E7AC3522405F0D0D1FC77205002481004C0814209A8800A0000031200C08171B571A2011
777000000000000022BB1C0008314626505F0E0EA20723060026A200540A1420AA8800A0000031200D091A1E621C2312
777000000000000022CC1C0029B54629605F0E0F2448D3060026A2005C0B1420AA8800A0000031200E0A1C206D1E2513
999000000000000022EE1C006BBD572F505F100F29C9B3070048C4005D0D14204A8900A000003120100C20247B202A13
999000000000000022FF1C008CC55834505F110F2D4A94080048C4005D0F14204A8900A000003120120D232889222E14
999000000000000022119D00ADCD693A705F111131CB7409004AE4006D0114204A8900A002003120140E272D97263215
999000000000000022229D00CE516A3E805F1212B40B450A004AE400750314204A8900A002003120150F2A30A4283516
999000000000000022449D00105A7B44805F1312B88C250B004C0401750514204A8900A00200312017112E34B22A3916
999000000000000022559D0031627C49905F1313BC0D060C004C04017D0714204A8900A00200312019123138C02D3D17
999000000000000022559D0031627C49905F1313BC0D060C004C04017D0714204A8900A00200312019123138C02D3D17

PBE 1.7.5

Please, fix it.

**Comment by IndeedMiners** [comment]
Send us the bios. H5GC8H24AJ was pretty common in 2017, so not sure what the problem is.

**Comment by mashkovtsev2006** [comment]
See attachment.See problem in attachment.See useful linkhttps://miningclub.info/threads/pamjat-h5gc8h24aj.56428/  21.01.2021, 23:06, "Indeed Miners" <notifications@github.com>: Send us the bios. H5GC8H24AJ was pretty common in 2017, so not sure what the problem is.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by IndeedMiners** [comment]
There is no attachment, you probably need to upload directly on Github not as email attachment. The thread is also 2 years old and I don't speak russian (Google Translate is not speaking very good russian too)
My bad I've confused H5GC8H24AJ for H5GC4H24AJ, but still both of them are supported in PBE. H5GC8H24AJ since 1.7.2.

**Comment by mashkovtsev2006** [comment]
https://yadi.sk/i/OBQ66JMxQA6mAw - problemhttps://yadi.sk/d/dFJemjZf1d3vvA - bios Dont read link, you can only test timings for this memory type.  22.01.2021, 14:46, "Indeed Miners" <notifications@github.com>: There is no attachment, you probably need to upload directly on Github not as email attachment. The thread is also 2 years old and I don't speak russian (Google Translate is not speaking very good russian too)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by IndeedMiners** [comment]
Thanks for the bios. I can reproduce the error. It works just fine, it applies correct timings. We will fix the error alert in next release. PBE PRO is completly fine with that, there is no error at all.

**Comment by IndeedMiners** [comment]
Fixed https://github.com/IndeedMiners/PolarisBiosEditor/releases/tag/1.7.6
