### ISSUE TITLE
"Sorry, no supported memory found"

### ISSUE THREAD

**Issue by erickrulz** [IndeedMiners/PolarisBiosEditor#13]
can anyone help me with this error

I have Gigabyte 570 8gb with hynix vram

iL attach the Bios

[newgiggbyterx570stockbios.zip](https://github.com/IndeedMiners/PolarisBiosEditor/files/5901286/newgiggbyterx570stockbios.zip)

THANK YOU!

**Comment by IndeedMiners** [comment]
Duplicate issue
https://github.com/IndeedMiners/PolarisBiosEditor/issues/12
