### ISSUE TITLE
XFX RX 580 with Hynix memory - getting a no supported Memory found error

### ISSUE THREAD

**Issue by Beiga11** [IndeedMiners/PolarisBiosEditor#15]
Hi,

I am getting the no supported memory error on an XFX RX 580 card.

![image](https://user-images.githubusercontent.com/70951366/108217544-a292e380-712b-11eb-94dd-242d58f17328.png)

Uploading the original ROM:

[20210217 bios_original_580.zip](https://github.com/IndeedMiners/PolarisBiosEditor/files/5996307/20210217.bios_original_580.zip)

Can this be fixed?

Thanks

**Comment by IndeedMiners** [comment]
https://github.com/IndeedMiners/PolarisBiosEditor/issues/12
Just a small bug, timings are applied correctly. It will be fixed in 1.7.6.

**Comment by elstukov** [comment]
> 
> 
> #12
> Just a small bug, timings are applied correctly. It will be fixed in 1.7.6.

In my case for MSI Armor OC RX 590 same memory, after flashing with the resulting bios (both universal and non universal timings) the gpu was then not recognized.
