### ISSUE TITLE
No supported memory found!

### ISSUE THREAD

**Issue by mortezahaidari** [IndeedMiners/PolarisBiosEditor#19]
Hello, 

I recently tried to bios mod the XFX Radeon rx 580 8GB GTS XXX Ed OC+, but still not lucky enough. 
Memory is hynix. 
Anyone with a solution in order for me to be able to bios mod it?

Best Regards 
Morteza

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
