### ISSUE TITLE
New Samsung Memory (K4G80325FC) on Gigabyte RX 590

### ISSUE THREAD

**Issue by juanjolozadap** [IndeedMiners/PolarisBiosEditor#2]
It isn't supported, as it is unknown. I've bought this Gigabyte RX 590 which is apparently called Rev. 2.0 (don't know what is revisioned). There Samsung memories (K4G80325FC) are "UNKNOWN" / not supported by current version of PBE 1.7.2

What is a bummer, is that I'm getting 27.5 MH/s on ETH/ETC, when previously, with my RX 580 8GB from Asrock, I was getting 30.5 MH/s, and I don't think I even had modded the BIOS (I could be mistaken, I can't remember well).

This RX 590 doesn't seem stable on 2200MHz VRAM on stock voltages. Only went up to 2175MHz and HWInfo showed Memory Errors.

I'm on Adrenaline drivers (I think this is the norm right now? Using the latest drivers?)
Drivers I tested: 19.9.2 and 19.11.3 --- both with similar results.

If I can get to at least 29/30 MH/s I would call it a day, but I was under the impression Samsung could do 31/33 MH/s, so I'm still disappointed. 

Here's a screen capture of Stock BIOS on my RX 590 as per seen on PBE 1.7.2
![ss pbe 172 un-supported samsung memories](https://user-images.githubusercontent.com/58301362/69815067-4b29f000-11d4-11ea-83c8-6b93ee9648ac.jpg)

Any help is appreciated.

**Comment by IndeedMiners** [comment]
Sorry for late reply, I will add support for that in few weeks. Could you try which Ubermix version fits your memory type the best? Thanks
https://www.overclock.net/forum/67-amd/1604567-polaris-bios-editing-rx5xx-rx4xx.html

**Comment by juanjolozadap** [comment]
Hey, man. I'm glad for your support.

I e-mailed you my BIOS to your address but got no reply. I want to know exactly hoy to do these tweaks myself, and if there might be any possible risks of 'bricking' the card before doing these.

I think my model doesn't have dual bios, or bios reset switch.

I would follow step by step your instructions. I will read on how to do that on the link you sent me (https://www.overclock.net/forum/67-amd/1604567-polaris-bios-editing-rx5xx-rx4xx.html) if there's any information there on how to do this.

I am here, I have this open in a separate tab, so I'll know when you reply to me. 

Let me know if you want to like get it done someday in real time somehow and we'll do it.
Cheers, Juan -

**Comment by dwd1** [comment]
Hi,
I have a new MSI RX 580 8GB Armor with this chip.
The stock BIOS is attached. [2738_msi5808_orig_kartyarol.zip](https://github.com/IndeedMiners/PBE-Polaris-Bios-Editor-1.7.2/files/4086469/2738_msi5808_orig_kartyarol.zip)

UberMix timing tests, 1500 and above:
UberMix 3.1, UberMix 2.3, UberMix 2.1: the card cannot create DAG, its do 0.000 MH/s
UberMix 3.3, UberMix 3.0: the PC simply resets when Claymore miner starting
UberMix 3.4: Claymore miner can start and create DAG and do 29.363 with stock GPU and mem clock but incorrect share and the PC crashes in minutes

So no UberMix version which works with this type of memory chip!

(If you want I can give you a Windows VNC with remote power switch and enabled motherboard video so you can make tests and can recover from bad flash.)

**Comment by juanjolozadap** [comment]
Thanks for the replies.

I haven't got time to put myself to test these things myself, and fear of damaging the card is far greater than my will to play around with it, unfortunately...

I think I'll just wait for a stable BIOS mod for this card, thoroughly tested back and forth, before venturing to modding it, or let alone, serve as a test dummy, given what I said.

IDK what a Windows VNC is yet, or a remote power switch, but I'll tell you my CPU is i3 9100F, so no on-board video for me; no integrated graphics. I depend solely on the GPU even for the motherboard BIOS to lit up... It seems I couldn't be of any help, if I wanted.

But let me know if there's a work-around.
Cheers

**Comment by dwd1** [comment]
VNC is a remote access software for Windows so you can connect to the test PC from your computer and can flash the MSI card for testing.
Remote power switch is good if you get ROM erase failed or another unrecoverable flash error, you can power-cycle the PC remotely (off-on) and the PC boots up so you can continue the flashing and the tests.
The default motherboard video output is good if the card is bad flashed, the PC can still boot up and can do another flashing to the card.

But of course I can wait to another timing for this card :)

**Comment by dwd1** [comment]
But of course I can wait to another timing for this card :)

**Comment by juanjolozadap** [comment]
@dwd1 I see. But unfortunately I don't have on-board graphics. Absolutely *need* a GPU, or a CPU with iGPU, even to boot the BIOS...

This is some stuff newest CPUs have (no iGPU) so they save some bucks in production, and in turn you save a few bucks in purchase. They also heat up less. It's kind of a gaming thing, and I have one of those, and no other, sadly.

I think otherwise I may've tried this, but seeing this is the case, I don't think I will.
Even if supposedly there's a working BIOS mod, I should stay off from it, unless I have the certainty I can correct the possibility of "fatal" error... but so far I don't think I can. 

I will look onto it, but I don't have my hopes high. Cheers

**Comment by IndeedMiners** [comment]
Hi guys,
again sorry for late reply, kinda busy.
Not sure who of you e-mailed me, but I've got some e-mails regarding the new Samsung memory, it might also end up in spam, but not really someone who would test the classic timings to know where to start with at least like @dwd1 did it, thaks for that! I will try to do new timing strap from the original one that will fit this type, so who want's to test please contact me via e-mail, the best timing will go to PBE PRO and some of the good ones in this free version, testers gets all of them. It's been a while since I've made timings, so we will need to test couple of them at least... 😄 

BTW try Uber-mix 3.2 it was actually pretty good on 2018/2019 RX 580 8GB cards.
777000000000000022CC1C00CEE55C46C0590E1532CD66090060070014051420FA8900A00300000012123442C3353C19

I haven't try the latest Uber-mix from 3.3+, so can't really tell how they perform on classic Samsung types anyway...

**Comment by dwd1** [comment]
@IndeedMiners, I will test the timing if you send it to me (my email is my username without the number @ my username without the number . hu)

**Comment by juanjolozadap** [comment]
@IndeedMiners (and @dwd1) 

Hi. I e-mailed you, but I'm afraid I don't have on-board graphics, or another graphics card, in case something goes really bad and I can't re-flash with the stock BIOS. I'm *really* scared of doing this, unless you guys can show me how it's done, but even then, I need to know for sure I won't screw up my GPU. I really want to help testing, but first I need to know I won't end up with a 200 USD ruined card.

If there would be any stable timings that guarantees not to screw me up my GPU I'll test it right away. Please provide with insight and guidance, so I can perhaps test this as you guys want me to.

Point me towards a clear guide to fully know what we're talking about here, and what exactly are the risks. Thank you for your understandings.

**Comment by BoriZka67** [comment]
Hi. I have a red Dragon from Power Color with this memory. The above timings did not fit (frequency 1150/2000). Ready for experiments. On stock timings at frequencies 1150/2150 gives 25.6 mh

**Comment by BoriZka67** [comment]
777000000000000022CC1C00106A6D4DD0571016B90D060C006AE70014051420FA8900A0030000001B11333DC0303A17
prescribed in 2000
core 1150 memory 2100
the result 29mh
when the memory frequency increases, it starts to crash.
If you find better timings, or you will get more out of it-please unsubscribe

**Comment by juanjolozadap** [comment]
Ok, unadvertently I can post something that might be of value...

I'm a noobie to mining so bare with me.

I am back to doing 30.5 MH/s ETH - Dual Claymore - Dagger Hashimoto

All I needed to do was set up "-strap 1" in configuration... so I went up from 27.1 to 30.5 MH/s

One note: I couldn't hold 2185MHz in these memories with that option set, but I'm apparently stable @ 2100MHz... 

Needs further testing, I might get away with 2150MHz or so, which would easily give me 31.low MH/s, which is what I expected from this card (RX 590)

I can't imagine what it could do with a proper BIOS mod, unless what I'm doing is already maxing it out other way.

**Comment by BoriZka67** [comment]
> Ok, unadvertently I can post something that might be of value...
> 
> I'm a noobie to mining so bare with me.
> 
> I am back to doing 30.5 MH/s ETH - Dual Claymore - Dagger Hashimoto
> 
> All I needed to do was set up "-strap 1" in configuration... so I went up from 27.1 to 30.5 MH/s
> 
> One note: I couldn't hold 2185MHz in these memories with that option set, but I'm apparently stable @ 2100MHz...
> 
> Needs further testing, I might get away with 2150MHz or so, which would easily give me 31.low MH/s, which is what I expected from this card (RX 590)
> 
> I can't imagine what it could do with a proper BIOS mod, unless what I'm doing is already maxing it out other way.

What timing and at what frequencies do you get 30.5?

**Comment by juanjolozadap** [comment]
> What timing and at what frequencies do you get 30.5?
Default BIOS on Gigabyte RX 590 Rev2.0
Only set up "-strap 1" on Dual Claymore
Will experiment with "-rxboost" as well, and possibly higher frequencies
Right now I'm stable at 2100MHz, but 2185 gave me artifacts
I'll test later today and post results. Didn't mod the BIOS.

**Comment by BoriZka67** [comment]
> > What timing and at what frequencies do you get 30.5?
> > Default BIOS on Gigabyte RX 590 Rev2.0
> > Only set up "-strap 1" on Dual Claymore
> > Will experiment with "-rxboost" as well, and possibly higher frequencies
> > Right now I'm stable at 2100MHz, but 2185 gave me artifacts
> > I'll test later today and post results. Didn't mod the BIOS.

I'm stable at 2120MHz = 29,32MH

**Comment by IndeedMiners** [comment]
Hi guys,
I've posted timings before, but seems like I didn't actually really does it or it ended up in Github spam :D
Try these 2 pls, let me know hashrate and memory clocks.
777000000000000022CC1C00106A6D4DD0571016B90D060C0060070014051420FA8900A0030000001B11333DC0303A17
777000000000000022CC1C00CE616C47D0571015B90D060C0060070014051420FA8900A0030000001B11333DC0303A17

**Comment by BoriZka67** [comment]
> Hi guys,
> I've posted timings before, but seems like I didn't actually really does it or it ended up in Github spam :D
> Try these 2 pls, let me know hashrate and memory clocks.
> 777000000000000022CC1C00106A6D4DD0571016B90D060C0060070014051420FA8900A0030000001B11333DC0303A17
> 777000000000000022CC1C00CE616C47D0571015B90D060C0060070014051420FA8900A0030000001B11333DC0303A17

first timing (777000000000000022CC1C00106A6D4DD0571016B90D060C0060070014051420FA8900A0030000001B11333DC0303A17) 1150/2120 give 29.9 MH,
second timing (777000000000000022CC1C00CE616C47D0571015B90D060C0060070014051420FA8900A0030000001B11333DC0303A17) 1150/2000 (maximum) all that is above to crash
I will continue to test the first timing, and I will update the results.

**Comment by BoriZka67** [comment]
> Hi guys,
> I've posted timings before, but seems like I didn't actually really does it or it ended up in Github spam :D
> Try these 2 pls, let me know hashrate and memory clocks.
> 777000000000000022CC1C00106A6D4DD0571016B90D060C0060070014051420FA8900A0030000001B11333DC0303A17
> 777000000000000022CC1C00CE616C47D0571015B90D060C0060070014051420FA8900A0030000001B11333DC0303A17

Found a new timing
777000000000000022CC1C00106A5D4DD0571016B90D060C0060070014051420FA8900A0030000001011333DC0303A17
1150/2100 give me 30.1MH...

**Comment by mrEckendonk** [comment]
@BoriZka67 I never did this before, but your timings (latest) increased temp to 51C without MSI afterburner. Cold start..... 👍 

![image](https://user-images.githubusercontent.com/30936842/75833120-ca602e80-5d96-11ea-988f-1ddf7788ae7f.png)

Only difference is the card, this is the RX580 ARMOR 8GB OC
![image](https://user-images.githubusercontent.com/30936842/75834977-6c364a00-5d9c-11ea-9086-8ad8f5f0b507.png)

The voltage is unstable, whooping for 1150mv to 1162mv.

New timings or timings for my card, welcome ! ! ! 💯

**Comment by mrEckendonk** [comment]
@IndeedMiners 
> BTW try Uber-mix 3.2 it was actually pretty good on 2018/2019 RX 580 8GB cards.
777000000000000022CC1C00CEE55C46C0590E1532CD66090060070014051420FA8900A00300000012123442C3353C19

This gave me a 29MH/z, one more, but did not work out well. Only errors and msi afterburner set to default.

**Comment by IndeedMiners** [comment]
@BoriZka67 Well, that's pretty much the same timing I did from 1750MHz stock, with one more change. We can do further more changes to see what it handles.
Just one change again if it can handle lower TCL
777000000000000022CC1C00106A5D4DD0571015B90D060C0060070014051420FA8900A0030000001011333DC0303A17
Few more changes
777000000000000022CC1C00106A5D4DC0570E15B90D060C0060070014051420FA8900A0030000001011333DC0303A17
Edit:
I found some old timings, that are actually made from the 1750 mhz mentioned above, didn't realize they used these timings for K4G80325FB too. But not sure if they trully works... only comment I have for one is that it's good for RX 580 8GB :D 
I will do closed BETA testing, who wants to test them write to monerobiosedit@gmail.com

@Eckybrazzz Yeah, it was just blind shot, no reason to further test Uber-mixes.

**Comment by BoriZka67** [comment]
> @BoriZka67 I never did this before, but your timings (latest) increased temp to 51C without MSI afterburner. Cold start..... 👍
> 
> ![image](https://user-images.githubusercontent.com/30936842/75833120-ca602e80-5d96-11ea-988f-1ddf7788ae7f.png)
> 
> Only difference is the card, this is the RX580 ARMOR 8GB OC
> ![image](https://user-images.githubusercontent.com/30936842/75834977-6c364a00-5d9c-11ea-9086-8ad8f5f0b507.png)
> 
> The voltage is unstable, whooping for 1150mv to 1162mv.
> 
> New timings or timings for my card, welcome ! ! ! 💯

cpu frequency 1465? оО

**Comment by kensagle** [comment]
Any updates?  I have the same memory in some XFX RX580 XXX 8GB cards.  Looking for bios mod.

**Comment by tgolo** [comment]
Hello, 
I dont know if this duscussion is still on going, but I have the same problem on a Sapphire RX 570 8GB (K4G80325FC). 
I can not mod teh BIOS with PBE 1.7.2, and I dont know what timings to use. 

Any one got some good stable timings ? 

Thanks in advance. 

TG

**Comment by tgolo** [comment]
Hello, 

Sorry for posting again. Based on he above discussion and the proposed timings, I did some reading this week and came up with this memory 2000 Mhz Strap (issued from the 1750): 

1100/2050 --> 30.535 in linux SMOS
1100/2150 --> 31.600 in linux SMOS

777000000000000022CC1C00106A6D4DD0571015B90D060C0060070014051420FA8900A0030000001B11333DC0303A17 

Best regards, 
T

**Comment by milpster** [comment]
> 
> 
> Hello,
> 
> Sorry for posting again. Based on he above discussion and the proposed timings, I did some reading this week and came up with this memory 2000 Mhz Strap (issued from the 1750):
> 
> 1100/2050 --> 30.535 in linux SMOS
> 1100/2150 --> 31.600 in linux SMOS
> 
> 777000000000000022CC1C00106A6D4DD0571015B90D060C0060070014051420FA8900A0030000001B11333DC0303A17
> 
> Best regards,
> T

Thank you sir!

Got a Msi Armor RX570 8G here with K4G80325FC and this is working good at 2000mhz so far. I tried all the Ubermixes before, with 3.4 being the one being stable at 1860 mhz and most other ubermixes not working at all.

I can upload all the bios files i have created for this card if anyone needs them.

Here is a performance comparison update:

![withnewstrapBW](https://user-images.githubusercontent.com/66098071/83266701-79a87800-a1c3-11ea-88c0-7a111d766bff.PNG)

So the bandwidth seems comparable to ubermix 3.4 at stable settings, however the OC headroom in terms of memory frequency is a lot bigger. A quick kombustor OC to 2170mhz seems stable so far:

![withnewstrapOCBW](https://user-images.githubusercontent.com/66098071/83266808-a0ff4500-a1c3-11ea-8e90-43c063915b79.PNG)

**Comment by soier333** [comment]
Throw off pliz bios under Windows I mine ether I also have this memory msi armor 570 oc - hash rate in stock 24.250 driver Crismon

**Comment by soier333** [comment]
> > Привет,
> > Извините за публикацию снова. Исходя из вышеизложенного, и предложенного времени, я немного почитал на этой неделе и придумал ремешок с памятью 2000 МГц (выпущенный с 1750 года):
> > 1100/2050 -> 30,535 в Linux SMOS 
> > 1100/2150 -> 31,600 в Linux SMOS
> > 777000000000000022CC1C00106A6D4DD0571015B90D060C0060070014051420FA8900A0030000001B11333DC0303A17
> > С наилучшими пожеланиями, 
> > T
> 
> Спасибо, сэр!
> 
> Получил Msi Armor RX570 8G здесь с K4G80325FC, и до сих пор он работает на частоте 2000 МГц. Я пробовал все Ubermixes прежде, с 3.4, который был стабильным на частоте 1860 МГц, и большинство других ubermixes не работали вообще.
> 
> Я могу загрузить все файлы BIOS, которые я создал для этой карты, если они кому-нибудь понадобятся.
> 
> Вот обновление сравнения производительности:
> 
> ![withnewstrapBW](https://user-images.githubusercontent.com/66098071/83266701-79a87800-a1c3-11ea-88c0-7a111d766bff.PNG)
> 
> Таким образом, пропускная способность кажется сравнимой с Ubermix 3.4 при стабильных настройках, однако запас OC с точки зрения частоты памяти намного больше. Быстрый комбустор OC до 2170 МГц пока выглядит стабильным:
> 
> ![withnewstrapOCBW](https://user-images.githubusercontent.com/66098071/83266808-a0ff4500-a1c3-11ea-8e90-43c063915b79.PNG)

throw off pliz bios under windows I mine broadcast I also have this hash rate in stock 24.250 video card like you msi rx 570 armor oc

**Comment by soier333** [comment]
throw off pliz bios under windows I mine broadcast I also have this hash rate in stock 24.250 video card like you msi rx 570 armor os memori K4G80325FC

**Comment by tgolo** [comment]
I also tried 1150/2100 and it is mining at 31.2 M stable for a week. We can push it to 32.5 but the cunsumption  and the temperature are higher, I dont know if it's worth it. 
Uber mix didn't work for me it was hanging in a few minutes. 
Best regards, 
T

**Comment by MeTRulez** [comment]
Hello there! I also have this (god damn) bios and I got no clue at all how to do the mod. can someone point me on how to apply the mod mentionned above? I don't understand 🤷🏼‍♂️

1100/2050 --> 30.535 in linux SMOS
1100/2150 --> 31.600 in linux SMOS

777000000000000022CC1C00106A6D4DD0571015B90D060C0060070014051420FA8900A0030000001B11333DC0303A17

**Comment by IndeedMiners** [comment]
1.7.3 Released with support for K4G80325FC
[https://github.com/IndeedMiners/PBE-Polaris-Bios-Editor-1.7.3/releases/tag/1.7.3](url)

**Comment by JayaKrishnaSK** [comment]
Hello Friends, am using Two Msi Armor RX570 8G with K4G80325FC and it can reach upto 26Mh. Please some one sent BIOS for these cards. Thanks is advance...

**Comment by soier333** [comment]
Hello! if you need these cards to give 26 ,you just need to install
adrenaline version 20.4.2, then go to the manual settings and change the
timings from automatic to level 2 and that's it !

чт, 24 сент. 2020 г. в 17:37, JayaKrishnaSK <notifications@github.com>:

**Comment by JayaKrishnaSK** [comment]
It can go upto 26 but I need to reach 29-30..

**Comment by JayaKrishnaSK** [comment]
> throw off pliz bios under windows I mine broadcast I also have this hash rate in stock 24.250 video card like you msi rx 570 armor os memori K4G80325FC

do you get any update because am also have the same problem..( jayakrishna.jainth@gmail.com ) my mail id please sent the mod BIOS for MSI RX 570 K4G80325FC card..

**Comment by JayaKrishnaSK** [comment]
should i change above timings to both 1750 and 2000 on bios.
