### ISSUE TITLE
Sorry, no supported memory found.

### ISSUE THREAD

**Issue by zumarek** [IndeedMiners/PolarisBiosEditor#20]
Hardware:
Radeon RX 580 8192 MB · MSI
SK Hynix H5GC8H24AJR 113-MSITV341MH.6M1

Anyone with the same issue?

**Comment by f0rtem** [comment]
> 
> 
> Hardware:
> Radeon RX 580 8192 MB · MSI
> SK Hynix H5GC8H24AJR 113-MSITV341MH.6M1
> 
> Anyone with the same issue?

Yes, got the same issue

**Comment by chruzie** [comment]
This may help you, but after loading in your default rom, you can actually export and save the ROM that is created (but unable to apply). Save that ROM somewhere and flash it anyways. using the ATI flashing tool.
I was able to get my MSI Hynix Armor RX 580 OC from 22 mH to 30mH.

**Comment by cryptominingarg** [comment]
> This may help you, but after loading in your default rom, you can actually export and save the ROM that is created (but unable to apply). Save that ROM somewhere and flash it anyways. using the ATI flashing tool.
> I was able to get my MSI Hynix Armor RX 580 OC from 22 mH to 30mH.

Hi, you flashe with ATI Flashing tool on HiveOS? is that possible? could you give me a little explanation how to make that?

**Comment by chruzie** [comment]
@cryptominingarg I flashed using the ATI flashing tool in my windows dual boot, then just rebooted to HiveOS.

**Comment by rbenal** [comment]
I got same error message,  my card is an MSI ARMOR RX 580  OC 8GB with hynix memory and was stucked at 23,MH/s, so i did what @chruzie wrote and it works, when the message appears i just click OK and then saved the flashed bios in my PC, then from HiveOS I uploaded that bio file to my card and it is working now at 31,3 MH/s

AMD specs of my cards from HiveOS: RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-MSITV341MH.6M1

**Comment by novelar** [comment]
> I got same error message, my card is an MSI ARMOR RX 580 OC 8GB with hynix memory and was stucked at 23,MH/s, so i did what @chruzie wrote and it works, when the message appears i just click OK and then saved the flashed bios in my PC, then from HiveOS I uploaded that bio file to my card and it is working now at 31,3 MH/s
> 
> AMD specs of my cards from HiveOS: RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-MSITV341MH.6M1

Can you upload or send me de moded bios? And the OC settings in from hiveOS. I did the same, one patch with Polaris, accept the warning message, flash it in HiveOS but I'm stuck at 24mh/s anyways. Thank you

**Comment by rbenal** [comment]
[MOD-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-MSITV341MH.6M1.rom.zip](https://github.com/IndeedMiners/PolarisBiosEditor/files/6470659/MOD-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-MSITV341MH.6M1.rom.zip)
![image](https://user-images.githubusercontent.com/4651013/118086452-61ad1280-b39a-11eb-9e7b-45fbc91ed66e.png)

![image](https://user-images.githubusercontent.com/4651013/118086574-90c38400-b39a-11eb-87bf-a70492101803.png)

**Comment by novelar** [comment]
I did the same, flash it anyways and its good thank you ! 

![image](https://user-images.githubusercontent.com/62145234/118212123-0e42cf00-b443-11eb-9c7f-3ed1c5368ada.png)

**Comment by rbenal** [comment]
@novelar you are welcome!

**Comment by minificando** [comment]
> @novelar you are welcome!

Sup, im searching for the ORIGINAL bios of the MSI rx 580 SK Hynix H5GC8H24AJR 113-MSITV341MH.6M1 , does someone has it? 

Thank you very much in advance for your help and have a nice day!
Regards

**Comment by rbenal** [comment]
> > @novelar you are welcome!
> 
> Sup, im searching for the ORIGINAL bios of the MSI rx 580 SK Hynix H5GC8H24AJR 113-MSITV341MH.6M1 , does someone has it?
> 
> Thank you very much in advance for your help and have a nice day!
> Regards

There you go my friend ...

[ORIGINAL-1-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-MSITV341MH.6M1-CARD-21-05-2021 (1).rom.zip](https://github.com/IndeedMiners/PolarisBiosEditor/files/6871512/ORIGINAL-1-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-MSITV341MH.6M1-CARD-21-05-2021.1.rom.zip)

**Comment by minificando** [comment]
> > > @novelar you are welcome!
> > 
> > 
> > Sup, im searching for the ORIGINAL bios of the MSI rx 580 SK Hynix H5GC8H24AJR 113-MSITV341MH.6M1 , does someone has it?
> > Thank you very much in advance for your help and have a nice day!
> > Regards
> 
> There you go my friend ...
> 
> [ORIGINAL-1-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-MSITV341MH.6M1-CARD-21-05-2021 (1).rom.zip](https://github.com/IndeedMiners/PolarisBiosEditor/files/6871512/ORIGINAL-1-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-113-MSITV341MH.6M1-CARD-21-05-2021.1.rom.zip)

gracias papa

**Comment by MrKingm4n** [comment]
Hi guys I had same error with XFX RX580 8gb hynix H5GC8H24AJ(ofc this show in Polaris Editor)
![Capture](https://user-images.githubusercontent.com/89859412/131531670-441a85a3-ad1e-488b-95ba-7d5d9cd99cb1.PNG)

**Comment by EmmaCanez** [comment]
@rbenal 
Hello anyone who has the original bios of the XfX Radeon Rx 580 Xxx Edition Oc 8gb K4G80325FC (SAMSUNG_2) ?

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
