### ISSUE TITLE
unsupported DeviceID 0x5249

### ISSUE THREAD

**Issue by samansaadat** [IndeedMiners/PolarisBiosEditor#22]
Hi,
I'm trying  to open XFX AMD RX5700 XT Bios that I exported from GPU-Z, but the polaris bios editor 1.7.5 shows me this error "unsupported DeviceID 0x5249",
is there any solution for this ?

thanks.

**Comment by IndeedMiners** [comment]
Only for Polaris GPU, not for newer ones.
