### ISSUE TITLE
Radeon RX 580 8192 MB · MSI SK Hynix H5GC8H24AJR 113-MSITV341MH.6M1 Sorry, no supported memory found. #20

### ISSUE THREAD

**Issue by cryptominingarg** [IndeedMiners/PolarisBiosEditor#23]
Hello, Tried to elevate hashrate of this GPU but get this message on polaris editor. could anyone help me to solve it?

![image](https://user-images.githubusercontent.com/82778625/115546055-f3819e00-a27a-11eb-824d-55b687c1a80c.png)

**Comment by rbenal** [comment]
Same problem with MSI Armor OC 8GB RX 580

![image](https://user-images.githubusercontent.com/4651013/116771054-b78acd80-aa1e-11eb-8221-6c29fc3e12f4.png)

**Comment by rbenal** [comment]
@cryptominingarg do you solve this issue ?

**Comment by cryptominingarg** [comment]
Nope. Did what thy told but didnt worked for me still 22mh.

**Comment by rbenal** [comment]
I am stuck at 23 Mh, do You have The link yo te solution they toldo You?

**Comment by cryptominingarg** [comment]
https://github.com/IndeedMiners/PolarisBiosEditor/issues/20

**Comment by novelar** [comment]
Same problem here with Armor OC 8GB

**Comment by bostitch** [comment]
Same problem on MSI RX580s. Any one find a solution?

**Comment by kratua07** [comment]
Same problem with Gigabyte RX580 8GB.
![Uploading B209141B-E4CA-47C8-ABDE-B46B04F005C1.jpeg…]()

**Comment by modi858** [comment]
same problem here with xfx rx580 8GB

**Comment by FedeVerstraeten** [comment]
Hi everyone! Maybe I have a solution. 

A few days ago I had the same problem when applying bios mod to my Radeon RX580 8Gb MSI Armor GPU with SK Hynix H5GC8H24AJR memory.
When I loaded the original .rom into PolarisBiosEditor and clicked "ONE CLICK TIMING PATCH", the program showed the same warning. I didn't care about this message and I applied the mod rom to my GPU  anyway across the HiveOS web platform. I follow this steps:

1. Download original GPU2 BIOS (.rom file) and backup it
2. Apply PATCH with ![Polaris Bios Editor](https://github.com/IndeedMiners/PolarisBiosEditor)
3. Save the mod rom in a different file.
4. Load the mod rom to modify the GPU from HiveOS
5. Reboot miner.
6. Apply new Overclock values (I used one of those recommended by HiveOS).
7. Shutdown & Boot in 30s
8. Pray if you believe in gods.

And the final result:
- GPU1 has no  bios mod
- GPU2 has bios mod
![image](https://user-images.githubusercontent.com/19780327/142425005-93c581fe-03b7-4693-8c62-15c3669df74e.png)
GP1 has biosmod

I share with you this thread from the hiveos forum that was very useful to me: [Help with armor rx 580 oc](https://forum.hiveos.farm/t/help-with-armor-rx-580-oc/30994)

Good luck!

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
