### ISSUE TITLE
Sorry, no supported memory 

### ISSUE THREAD

**Issue by M0kii** [IndeedMiners/PolarisBiosEditor#25]
Im rocking Gigabyte Gaming RX 570 8GB's and this error shows up. I apply modded bios anyway but it doesnt recognise the gpu anymore.

**Comment by partycat133** [comment]
+1 with declared memory support H5GC8H24AJ on Gigabyte Gaming RX 580 8 GB this error shows up.

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
