### ISSUE TITLE
no supported memory found, ASUS RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-115-D009PI2-101

### ISSUE THREAD

**Issue by yeniceirl** [IndeedMiners/PolarisBiosEditor#27]
Hi, I tried raising the hashrate of this GPU but got the message: "no supported memory found"

ASUS RadeonRX580-8G-SK_Hynix_H5GC8H24AJR-115-D009PI2-101

**Comment by fgplastina** [comment]
I'm getting the same message on a Gigabyte RX580 8GB. Did you find something?

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
