### ISSUE TITLE
Hynix Memory H5GC8H24AJ  RX 590 Memory Not Supported  (gpu not recognized afterwards)

### ISSUE THREAD

**Issue by elstukov** [IndeedMiners/PolarisBiosEditor#28]
GPU is a MSI Armor RX 590 OC With Hynix H5GC8H24AJ Memory

This happens with either Universal or No Universal Hynix timings. Then if the bios is used to flash the GPU, then the GPU is not recognized. (Had to go to stock bios to make it work again)
Attached is stock bios.
[Stock Bios - MSI RX 590 Armor OC.zip](https://github.com/IndeedMiners/PolarisBiosEditor/files/6911946/Stock.Bios.-.MSI.RX.590.Armor.OC.zip)

![image](https://user-images.githubusercontent.com/88256318/127754791-fc95d66c-233e-43ea-b4bf-8be03d8bc5a3.png)

**Comment by awdwas** [comment]
same here 2nd_floor-4-RadeonRX580-8G-SK_Hynix_H5GC8H24AJR

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
