### ISSUE TITLE
Sorry , No supported Memory

### ISSUE THREAD

**Issue by MrKingm4n** [IndeedMiners/PolarisBiosEditor#29]
Hi guys I tried to solve this problem by way in #20 and https://github.com/IndeedMiners/PolarisBiosEditor/issues/20#issuecomment-909344745

I'm working on hiveOS
I tried to flashing MSI bios but I received new error in hiveos
could you help me?
![Uploading Capture.PNG…]()

**Comment by MrKingm4n** [comment]
![Capture](https://user-images.githubusercontent.com/89859412/131538718-1b5dd2a2-85d9-4d46-b24a-6187b708ee47.PNG)

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
