### ISSUE TITLE
AFOX Rx580 8gb, Hynix H5GQ8H24MJR - ``No supported memory found``

### ISSUE THREAD

**Issue by mjhiroki** [IndeedMiners/PolarisBiosEditor#30]
I think that AFOX in this version blocks to change bio mod. 

AFOX Rx580 8gb 8192 MB, GDDR5, Hynix H5GQ8H24MJR

![WhatsApp Image 2021-09-02 at 22 59 58](https://user-images.githubusercontent.com/84207372/131939634-2dc4861e-ef68-48da-b9dd-cb51b771c1a6.jpeg)

**Comment by awdwas** [comment]
Same here, Tried previous versions not working,
RadeonRX580-8G-SK_Hynix_H5GC8H24AJR

**Comment by modi858** [comment]
Same here 
please fix

**Comment by JoaquinAkerman** [comment]
Same here, 580 Hynix memory

**Comment by JoaquinAkerman** [comment]
I found a modified bios for the 580 afox 8gb, works only with hynix memory. Email me to joaquin_akerman@hotmail.com

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
