### ISSUE TITLE
no supported memory found H5GC8H24AJ (HYNIX_4)

### ISSUE THREAD

**Issue by mahdi1944** [IndeedMiners/PolarisBiosEditor#32]
Hi, 

My rx580 memory is H5GC8H24AJ (HYNIX_4) and not found in polaris bios editor 1.7.5, please update and support my card

Thanks

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
