### ISSUE TITLE
doesn't memory support error on pbe v1.7.5 for xfx rx590 gme 3f H5GC8H24AJ (HYNIX_4)

### ISSUE THREAD

**Issue by organic2** [IndeedMiners/PolarisBiosEditor#35]
I have problem to mod and unlock my rom with free pbe 1.7.5
anyone tried pbe pro 3 2020 version?

xfx rx590 gme 3fan 8gb
C940 Polaris20 XTX A1 GDDR5 256Mx32 8GB 300e/400m 
H5GC8H24AJ (HYNIX_4)
this is my rom. I've upload it
ufile.io/nmsch9pe
some one can test it for me or 'one click timing patch' with free or pro version of Polaris bios editor and send it back to me by email? thank you some much . setting: os Linux . oc and undervolt . eth
organic_classic@yahoo.com

**Comment by IndeedMiners** [comment]
1.7.6
