### ISSUE TITLE
Not Working For 6800 & 6800XT

### ISSUE THREAD

**Issue by SuperAlvis** [IndeedMiners/PolarisBiosEditor#36]
Dear team,

Greetings.

I tried to do some BIOS setting for 6800 & 6800XT. However when I tried to load the bios via polaris, it appear a warning message that "This BIOS is non standard size. Flashing this BIOS may corrupt your graphic card" "Unsupported DeviceID 0x3 - Continue?" ""Unhandled exception has occured in your application. If you click Continue, the application will ignore this error and attempt to continue xxxxxxxxxxxxxxxxxxxx. InvalidArgument=Value of '0' is not valid for 'SelectedIndex'. Parameter name: SelectedIndex."

Please advice.

Thanks

**Comment by IndeedMiners** [comment]
Only for Polaris GPU not for newer ones.
