### ISSUE TITLE
sorry, no supported memory found

### ISSUE THREAD

**Issue by mehdi535** [IndeedMiners/PolarisBiosEditor#37]
Hi, I'm getting this error when trying One Click Timing Patch on my RX 580 8gb Rom. My memory is a Hynix one.
please guide.
I attached the rom file as pdf.
[RadeonRX580-8G-SK_Hynix_Default-W90.pdf](https://github.com/IndeedMiners/PolarisBiosEditor/files/7538725/RadeonRX580-8G-SK_Hynix_Default-W90.pdf)
.

**Comment by FedeVerstraeten** [comment]
Hi, I had the same problem and I commented my "solution" in this issue https://github.com/IndeedMiners/PolarisBiosEditor/issues/23

Good luck!

**Comment by IndeedMiners** [comment]
Fixed in PBE [1.7.6](https://github.com/IndeedMiners/PolarisBiosEditor/releases/)
