### ISSUE TITLE
RX560 won´t work properly after bios mod

### ISSUE THREAD

**Issue by mrjjomen** [IndeedMiners/PolarisBiosEditor#38]
I saved original stock bios, used editor and made the one click timing mod.
Flashed modded bios. Restarted. 
Clicked remove and reinstalled driver via device manager in WIn10.
Status is ok in device manager. However AMD software neither miner cannot find the device.
What did I do wrong ?
Card used to work fine and I can get it working by flashing back stock bios.
I understand I might need to set the compute mode but I cannot access card by any means other than flash tool.

BR JJ

**Comment by IndeedMiners** [comment]
You need to patch the drivers
https://www.monitortests.com/forum/Thread-AMD-ATI-Pixel-Clock-Patcher
https://github.com/IndeedMiners/PolarisBiosEditor/wiki/POLARIS-BIOS-EDITOR-FAQ---BIOS-MOD#how-to-flash-modded-bios-to-your-gpu
