### ISSUE TITLE
No Supported memory for Samsung

### ISSUE THREAD

**Issue by shrik8968** [IndeedMiners/PolarisBiosEditor#6]
Attached screenshot is the error I'm receiving when trying to mod my GPU, the one that is working for samsung is for K4G80325FB (SAMSUNG), but my GPU has K4G80325FC (SAMSUNG_2). It is a different version

![Capture](https://user-images.githubusercontent.com/67523655/85933136-77037600-b888-11ea-8024-6bdcf0b9e5e9.PNG)

**Comment by shrik8968** [comment]
I have the latest version 1.7.3

**Comment by shrik8968** [comment]
![Capture1](https://user-images.githubusercontent.com/67523655/85933190-2d675b00-b889-11ea-86b2-9509618e89ae.PNG)

**Comment by shrik8968** [comment]
Found out the device id is new and it is not present in PolarisBiosEditor.cs. The new id is x1002

**Comment by IndeedMiners** [comment]
Strange, according to picture you have posted, PBE is detected Samsung_2 correctly and even applied modded timings at 1750 and 2000 Mhz. So it should be showing no error at all. Anyone else with this problem?
I only got some complaints for stability issue with these timings... but there are 2 for that so try both. Also timing strap for K4G80325FC in PBE 3 Pro 2020 is the most stable of them and of course performing a bit better. Still it isn't top notch, but good enough.

**Comment by raypnut** [comment]
Yes I'm experiencing the same issue
![1](https://user-images.githubusercontent.com/65230955/87088314-6a1c4600-c1e9-11ea-97dc-16b08c8a3f4d.PNG)
![2](https://user-images.githubusercontent.com/65230955/87088315-6ab4dc80-c1e9-11ea-865f-65e06e9a62b8.PNG)
![3](https://user-images.githubusercontent.com/65230955/87088316-6ab4dc80-c1e9-11ea-9c63-c2e40e9dd686.PNG)

**Comment by IndeedMiners** [comment]
@raypnut upload your bios please. There is bug with indexing, which I forget to fix, but it shouldn't be a problem except the wrong index number.

**Comment by raypnut** [comment]
Thanks for your reply @IndeedMiners ! This is the bios:
[Bios_RX_580.zip](https://github.com/IndeedMiners/PBE-Polaris-Bios-Editor-1.7.3/files/4917554/Bios_RX_580.zip)

**Comment by IndeedMiners** [comment]
@raypnut thanks for the upload. I will debug that later. It might actually be because of the indexing or I forget something else will check that... But anyway, it applies correct timings so you can try to flash it to your card, it should be working with no issue.

**Comment by IndeedMiners** [comment]
Should be fixed in 1.7.4, please test.

**Comment by IndeedMiners** [comment]
Fixed in 1.7.4
